/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 .\public\bahut\bahut.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/bahut.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.upper_01.geometry} material={nodes.upper_01.material} position={[0, 0.787, 0]} scale={0.01} />
      <mesh geometry={nodes.Lateral_01.geometry} material={nodes.Lateral_01.material} position={[0, 0.787, 0]} scale={0.01} />
      <mesh geometry={nodes.Lateral_02.geometry} material={nodes.Lateral_02.material} position={[0, 0.787, 0]} scale={0.01} />
      <mesh geometry={nodes.Front_03.geometry} material={nodes.Front_03.material} position={[0, 0.787, 0]} scale={0.01} />
      <mesh geometry={nodes.Front_04.geometry} material={nodes.Front_04.material} position={[0, 0.787, 0]} scale={0.01} />
      <mesh geometry={nodes.Front_05.geometry} material={nodes.Front_05.material} position={[0, 0.787, 0]} scale={0.01} />
      <mesh geometry={nodes.Front_01.geometry} material={nodes.Front_01.material} position={[0, 0.787, 0]} scale={0.01} />
      <mesh geometry={nodes.Front_02.geometry} material={nodes.Front_02.material} position={[0, 0.787, 0]} scale={0.01} />
      <mesh geometry={nodes.Legs.geometry} material={nodes.Legs.material} position={[0, 0.787, 0]} scale={0.01} />
      <mesh geometry={nodes.down_01.geometry} material={nodes.down_01.material} position={[0, 0.787, 0]} scale={0.01} />
      <mesh geometry={nodes.Back_01.geometry} material={nodes.Back_01.material} position={[0, 0.787, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/bahut.glb')
