/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/cobra_02/cobra_to_threjs.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cobra_to_threjs.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object004.geometry} material={nodes.Object004.material} position={[0.019, 0.384, -0.043]} />
      <mesh geometry={nodes.Object005.geometry} material={nodes.Object005.material} position={[0.006, 0.24, -0.028]} />
      <mesh geometry={nodes.Object006.geometry} material={nodes.Object006.material} position={[-0.005, 0.399, -0.015]} />
      <mesh geometry={nodes['5327684__240221P001'].geometry} material={nodes['5327684__240221P001'].material} position={[0.007, 0.036, -0.068]} />
    </group>
  )
}

useGLTF.preload('/cobra_to_threjs.glb')
