/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/lampe_01/lampe_01.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/lampe_01.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.abat_jour.geometry} material={nodes.abat_jour.material} position={[0, 0.487, -0.007]} />
      <mesh geometry={nodes.Object001.geometry} material={nodes.Object001.material} position={[0, 0.487, -0.007]} />
    </group>
  )
}

useGLTF.preload('/lampe_01.glb')
