/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/sofa_02/sofa_02_1k.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/sofa_02_1k.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.sofa_02_Base.geometry} material={materials.sofa_02} position={[0, 0, 0.031]} />
      <mesh geometry={nodes.sofa_02_Seat.geometry} material={materials.sofa_02} position={[0, 0, 0.031]} />
    </group>
  )
}

useGLTF.preload('/sofa_02_1k.gltf')
