/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/sofa_visio/sofa_visio.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/sofa_visio.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.part_01.geometry} material={nodes.part_01.material} position={[0, 0.004, 0]} scale={0.01} />
      <mesh geometry={nodes.part_02.geometry} material={nodes.part_02.material} position={[-0.887, 0.393, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/sofa_visio.glb')
