/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/woven_chair/woven_chair.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/woven_chair.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Aset_props__M_wjglah2s_00_LOD5.geometry} material={nodes.Aset_props__M_wjglah2s_00_LOD5.material} />
    </group>
  )
}

useGLTF.preload('/woven_chair.gltf')
