/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/sofa/sofa_yellow.gltf 
*/

import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Sofa = (props) => {
    const group = useRef()
    const { nodes, materials } = useGLTF('./sofa/sofa_yellow.gltf')

    return (
        <group ref={group} {...props} dispose={null} rotation={[0,Math.PI,0]} >
            <group name="Scene" >
                <mesh name="sofa" geometry={nodes.sofa.geometry} material={materials['default']} position={[0.118, 0.352, -0.125]} scale={0.01} />
            </group>
        </group>
    )
}
export default Sofa
